apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: farm-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wailwinphone/img-website.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true