apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-website
  labels:
    app: farm-website
    type: farm  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farm-website
  template:
    metadata:
      labels:
        app: farm-website
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: images-volume
          mountPath: /usr/share/nginx/html/images
      volumes:
      - name: website-html
        configMap:
          name: website-html
      - name: images-volume
        persistentVolumeClaim:
          claimName: animal-images-pvc