apiVersion: apps/v1
kind: Deployment
metadata:
  name: img-website
  labels:
    app: img-website
    type: wild  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-website
  template:
    metadata:
      labels:
        app: img-website
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-html
          mountPath: /usr/share/nginx/html
        - name: images-volume
          mountPath: /usr/share/nginx/html/images
      volumes:
      - name: website-html
        configMap:
          name: website-html
      - name: images-volume
        persistentVolumeClaim:
          claimName: farm-images-pvc