apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: animal-images-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-storage