apiVersion: v1
kind: ConfigMap
metadata:
  name: website-html
  labels:
    app: img-website
    type: farm  
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Farm Animals</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
          background-color: #f5f5dc;
        }
        h1 {
          color: #8B4513;
          text-align: center;
          padding: 20px;
          background-color: #F0E68C;
          border-radius: 10px;
        }
        .animals {
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          gap: 20px;
        }
        .animal-card {
          border: 1px solid #ddd;
          border-radius: 10px;
          padding: 15px;
          width: 300px;
          background-color: white;
          box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .animal-card img {
          width: 100%;
          height: 200px;
          object-fit: cover;
          border-radius: 5px;
        }
        .animal-card h2 {
          color: #8B4513;
          margin-top: 10px;
        }
        .animal-card p {
          color: #555;
        }
      </style>
    </head>
    <body>
      <h1>Farm Animals Gallery</h1>
      <div class="animals">
        <div class="animal-card">
          <img src="/images/tiger.jpg" alt="Tiger">
          <h2>Cow</h2>
          <p>Domesticated animal that provides milk and meat. Known for their gentle nature and important role in agriculture.</p>
        </div>
        <div class="animal-card">
          <img src="/images/chicken.jpeg" alt="Chicken">
          <h2>Chicken</h2>
          <p>Common farm bird that provides eggs and meat. They're social animals with complex hierarchical structures.</p>
        </div>
        <div class="animal-card">
          <img src="/images/lion.jpg" alt="Lion">
          <h2>Horse</h2>
          <p>Raised for wool, milk, and meat. Sheep are gentle herbivores with impressive memory for faces.</p>
        </div>
      </div>
    </body>
    </html>