apiVersion: v1
kind: ConfigMap
metadata:
  name: website-html
  labels:
    app: img-website
    type: wild  
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Farm Animals</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
          background-color: #f5f5dc;
        }
        h1 {
          color: #8B4513;
          text-align: center;
          padding: 20px;
          background-color: #F0E68C;
          border-radius: 10px;
        }
        .animals {
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          gap: 20px;
        }
        .animal-card {
          border: 1px solid #ddd;
          border-radius: 10px;
          padding: 15px;
          width: 300px;
          background-color: white;
          box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        .animal-card img {
          width: 100%;
          height: 200px;
          object-fit: cover;
          border-radius: 5px;
        }
        .animal-card h2 {
          color: #8B4513;
          margin-top: 10px;
        }
        .animal-card p {
          color: #555;
        }
      </style>
    </head>
    <body>
      <h1>Wild Animals</h1>
      <div class="animals">
        <div class="animal-card">
          <img src="/images/tiger.jpg" alt="Tiger">
          <h2>Tiger</h2>  <!-- Changed from Cow to Tiger -->
          <p>Powerful carnivore and the largest cat species. Known for their distinctive orange coat with black stripes.</p>
        </div>
      </div>
    </body>
    </html>